// Auto-generated by scripts/scrape-products.ts --consolidate on 2026-05-26T18:29:09.561Z
// Source: scripts/data/scraped/*.json (Firecrawl-scraped product data).
// Seed: npm run db:seed-products

export const AMAZON_AFFILIATE_TAG = "ahorrhogar-21";

export interface SeedProduct {
  slug: string;
  name: string;
  brand: string;
  categoryPath: string[];
  description: string;
  specs: Record<string, unknown>;
  attributes: Record<string, unknown>;
  imageUrl: string;
  offers: Array<{
    merchant: string;
    merchantDomain: string;
    price: number;
    oldPrice: number | null;
    url: string;
    scrapedAt: string;
  }>;
  sourceArticles: string[];
  confidence: number;
}

export const PRODUCTS: SeedProduct[] = [
  {
    "slug": "aeg-bpe948330m",
    "name": "AEG A9OZS10 - Maxiklasse Steam Set for Steam Cooking Suitable for All Steam Ovens",
    "brand": "AEG",
    "categoryPath": [
      "electrodomesticos",
      "grandes-electrodomesticos"
    ],
    "description": "AEG A9OZS10 - Maxiklasse Steam Set for Steam Cooking Suitable for All Steam Ovens — AEG BPE948330M SteamPro — premium con vapor (referenced in top-10-hornos-piroliticos-calidad-precio-2026)",
    "specs": {
      "slug": "aeg-bpe948330m",
      "rating": 4.6
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.06666666666666667
    },
    "imageUrl": "https://m.media-amazon.com/images/I/61GZ5NUf1SL._AC_SS115_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 37.18,
        "oldPrice": null,
        "url": "https://www.amazon.es/AEG-9029794741-Maxiklassetm-Steam-para-cocci%C3%B3n/dp/B00I99V6Z2?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:24:14.297Z"
      }
    ],
    "sourceArticles": [
      "top-10-hornos-piroliticos-calidad-precio-2026"
    ],
    "confidence": 0.06666666666666667
  },
  {
    "slug": "aktive-garden-tumbona-plegable-5-posiciones",
    "name": "AKTIVE 62616 – Folding Lounger 5 Positions Sailor Stripes 59 x 59 x 109 cm Garden",
    "brand": "AKTIVE",
    "categoryPath": [
      "jardin-exterior",
      "muebles-jardin"
    ],
    "description": "AKTIVE 62616 – Folding Lounger 5 Positions Sailor Stripes 59 x 59 x 109 cm Garden — Aktive Garden 5 posiciones (referenced in mejores-tumbonas-resistentes-jardin-verano-2026)",
    "specs": {
      "slug": "aktive-garden-tumbona-plegable-5-posiciones",
      "rating": 3.3,
      "reviewcount": 43
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.16666666666666666
    },
    "imageUrl": "https://m.media-amazon.com/images/I/71r1ym0TjqS._AC_SY300_SX300_QL70_ML2_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 85,
        "oldPrice": null,
        "url": "https://www.amazon.es/AKTIVE-62616-plegable-posiciones-marineras/dp/B089NKHWVY?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:21:16.785Z"
      }
    ],
    "sourceArticles": [
      "mejores-tumbonas-resistentes-jardin-verano-2026"
    ],
    "confidence": 0.16666666666666666
  },
  {
    "slug": "armario-2-puertas-correderas-kit-closet",
    "name": "VASAGLE LHC40W Bathroom Standing Storage Cabinet with 4 Drawers, 30 x 30 x 82 cm, Living Room, Dining Room, Kitchen, Modern Style, White",
    "brand": "VASAGLE",
    "categoryPath": [
      "muebles",
      "muebles-salon"
    ],
    "description": "VASAGLE LHC40W Bathroom Standing Storage Cabinet with 4 Drawers, 30 x 30 x 82 cm, Living Room, Dining Room, Kitchen, Modern Style, White — Armario (referenced in como-amueblar-habitacion-juvenil-menos-800-euros-2026)",
    "specs": {
      "slug": "armario-2-puertas-correderas-kit-closet",
      "rating": 4.5,
      "reviewcount": 554
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0
    },
    "imageUrl": "https://m.media-amazon.com/images/I/61JwD3OK+pL._AC_SX679_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 41.31,
        "oldPrice": null,
        "url": "https://www.amazon.es/SONGMICS-Armario-almacenaje-Organizador-cajones/dp/B01NADUXZP?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:21:21.793Z"
      }
    ],
    "sourceArticles": [
      "como-amueblar-habitacion-juvenil-menos-800-euros-2026"
    ],
    "confidence": 0
  },
  {
    "slug": "balay-3bc998hx",
    "name": "Cata Decorative Range Hood Legend Island 5 Levels of Extraction Touch Control Panel with Automatic Shut-off Timer Extra Quiet Motor LED Lighting Width 90 cm Stainless Steel : 502.15",
    "brand": "Cata",
    "categoryPath": [
      "electrodomesticos",
      "grandes-electrodomesticos"
    ],
    "description": "Cata Decorative Range Hood Legend Island 5 Levels of Extraction Touch Control Panel with Automatic Shut-off Timer Extra Quiet Motor LED Lighting Width 90 cm Stainless Steel : 502.15 — Decorativas (incluye isla, pared, cristal y forma de T) (referenced in campanas-extractoras-decorativas-vs-telescopicas-comparativa-2026)",
    "specs": {
      "slug": "balay-3bc998hx",
      "rating": 3.7,
      "reviewcount": 980
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0
    },
    "imageUrl": "https://m.media-amazon.com/images/I/61CfZ+z6Y7L._AC_SS115_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 229.8,
        "oldPrice": null,
        "url": "https://www.amazon.es/Cata-Extractora-Silencioso-Eficiencia-Energ%C3%A9tica/dp/B015KFY6H2?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:21:20.930Z"
      }
    ],
    "sourceArticles": [
      "campanas-extractoras-decorativas-vs-telescopicas-comparativa-2026"
    ],
    "confidence": 0
  },
  {
    "slug": "balay-3bt263mx",
    "name": "Balay - Telescopic Range Hood, 60 cm Width, Recirculation Installation, Stainless Steel, 3BT263MX",
    "brand": "Balay",
    "categoryPath": [
      "electrodomesticos",
      "grandes-electrodomesticos"
    ],
    "description": "Balay - Telescopic Range Hood, 60 cm Width, Recirculation Installation, Stainless Steel, 3BT263MX — Telescópicas (integradas en mueble) (referenced in campanas-extractoras-decorativas-vs-telescopicas-comparativa-2026)",
    "specs": {
      "slug": "balay-3bt263mx",
      "rating": 4.2
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.15384615384615385
    },
    "imageUrl": "https://m.media-amazon.com/images/I/516emFULEJL._AC_SS115_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 98.35,
        "oldPrice": null,
        "url": "https://www.amazon.es/Balay-3BT263MX-Telesc%C3%B3pica-extraplana-inoxidable/dp/B071LQX4H4?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:21:23.464Z"
      }
    ],
    "sourceArticles": [
      "campanas-extractoras-decorativas-vs-telescopicas-comparativa-2026"
    ],
    "confidence": 0.15384615384615385
  },
  {
    "slug": "balay-3eb914lr",
    "name": "Balay Ceramic Hob, Black, 60 cm : 166.98",
    "brand": "Balay",
    "categoryPath": [
      "electrodomesticos",
      "grandes-electrodomesticos"
    ],
    "description": "[![Free delivery on first orders message](https://m.media-amazon.com/images/I/31pWJ-XZqeL.jpg)](https://www.amazon.es/-/en/b/?_encoding=UTF8&node=18978330031&pd_rd_w=Gf47x&content-id=amzn1.sym.57bf98f3-83ad-485b-88b5-01efff37ea63&pf_rd_p=57bf98f3-83ad-485b-88b5-01efff37ea63&pf_rd_r=B6CT681CFQT8T1B49TNV&pd_rd_wg=OCnc5&pd_rd_r=ecf63484-2bb4-4d01-b42c-1c8678340c46)",
    "specs": {
      "slug": "balay-3eb914lr",
      "longdescription": "[![Free delivery on first orders message](https://m.media-amazon.com/images/I/31pWJ-XZqeL.jpg)](https://www.amazon.es/-/en/b/?_encoding=UTF8&node=18978330031&pd_rd_w=Gf47x&content-id=amzn1.sym.57bf98f3-83ad-485b-88b5-01efff37ea63&pf_rd_p=57bf98f3-83ad-485b-88b5-01efff37ea63&pf_rd_r=B6CT681CFQT8T1B49TNV&pd_rd_wg=OCnc5&pd_rd_r=ecf63484-2bb4-4d01-b42c-1c8678340c46)",
      "rating": 4.1
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.1111111111111111
    },
    "imageUrl": "https://m.media-amazon.com/images/I/71Fn5SVKSvL._AC_SS57_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 6,
        "oldPrice": null,
        "url": "https://www.amazon.es/Balay-3EB714XR-vitrocer%C3%A1mica-Vidrio-cer%C3%A1mica/dp/B00BIF6UFA?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:25:11.158Z"
      }
    ],
    "sourceArticles": [
      "placas-induccion-vs-vitroceramica-vs-gas-comparativa-precios-consumo"
    ],
    "confidence": 0.1111111111111111
  },
  {
    "slug": "balay-3eb967lu",
    "name": "Balay Ceramic Hob, Black, 60 cm : 166.98",
    "brand": "Balay",
    "categoryPath": [
      "electrodomesticos",
      "grandes-electrodomesticos"
    ],
    "description": "[![Free delivery on first orders message](https://m.media-amazon.com/images/I/31pWJ-XZqeL.jpg)](https://www.amazon.es/-/en/b/?_encoding=UTF8&node=18978330031&pd_rd_w=Gf47x&content-id=amzn1.sym.57bf98f3-83ad-485b-88b5-01efff37ea63&pf_rd_p=57bf98f3-83ad-485b-88b5-01efff37ea63&pf_rd_r=B6CT681CFQT8T1B49TNV&pd_rd_wg=OCnc5&pd_rd_r=ecf63484-2bb4-4d01-b42c-1c8678340c46)",
    "specs": {
      "slug": "balay-3eb967lu",
      "longdescription": "[![Free delivery on first orders message](https://m.media-amazon.com/images/I/31pWJ-XZqeL.jpg)](https://www.amazon.es/-/en/b/?_encoding=UTF8&node=18978330031&pd_rd_w=Gf47x&content-id=amzn1.sym.57bf98f3-83ad-485b-88b5-01efff37ea63&pf_rd_p=57bf98f3-83ad-485b-88b5-01efff37ea63&pf_rd_r=B6CT681CFQT8T1B49TNV&pd_rd_wg=OCnc5&pd_rd_r=ecf63484-2bb4-4d01-b42c-1c8678340c46)",
      "rating": 4.1
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.1111111111111111
    },
    "imageUrl": "https://m.media-amazon.com/images/I/71Fn5SVKSvL._AC_SS57_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 6,
        "oldPrice": null,
        "url": "https://www.amazon.es/Balay-3EB714XR-vitrocer%C3%A1mica-Vidrio-cer%C3%A1mica/dp/B00BIF6UFA?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:24:50.490Z"
      }
    ],
    "sourceArticles": [
      "placas-induccion-vs-vitroceramica-vs-gas-comparativa-precios-consumo"
    ],
    "confidence": 0.1111111111111111
  },
  {
    "slug": "balay-3etg663hb",
    "name": "Balay - Gas Hob, 3 Burners, 60 cm wide, Flame Control, GasStop Safety, Butane Gas Ready, Black, 3ETG663HB : 252.89",
    "brand": "Balay",
    "categoryPath": [
      "electrodomesticos",
      "grandes-electrodomesticos"
    ],
    "description": "Balay - Gas Hob, 3 Burners, 60 cm wide, Flame Control, GasStop Safety, Butane Gas Ready, Black, 3ETG663HB : 252.89 — Gas: cuándo encaja (referenced in placas-induccion-vs-vitroceramica-vs-gas-comparativa-precios-consumo)",
    "specs": {
      "slug": "balay-3etg663hb",
      "rating": 4.2,
      "reviewcount": 359
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.1875
    },
    "imageUrl": "https://m.media-amazon.com/images/I/616oAq7xzML._AC_SS115_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 60,
        "oldPrice": null,
        "url": "https://www.amazon.es/Balay-3ETG663HB-Integrado-Encimera-Negro/dp/B01LWA4L8B?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:24:48.210Z"
      }
    ],
    "sourceArticles": [
      "placas-induccion-vs-vitroceramica-vs-gas-comparativa-precios-consumo"
    ],
    "confidence": 0.1875
  },
  {
    "slug": "balay-3ts985ba",
    "name": "ReleMat - Original 128BH0004 hatch rubber for Balay washing machines",
    "brand": "ReleMat",
    "categoryPath": [
      "electrodomesticos",
      "grandes-electrodomesticos"
    ],
    "description": "ReleMat - Original 128BH0004 hatch rubber for Balay washing machines — Lavadora carga frontal: cuando encaja (referenced in lavadoras-carga-frontal-vs-superior-comparativa-precios-prestaciones)",
    "specs": {
      "slug": "balay-3ts985ba",
      "rating": 4.4
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.05555555555555555
    },
    "imageUrl": "https://m.media-amazon.com/images/I/31ISwh+TBmL._AC_SR38,50_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 40,
        "oldPrice": null,
        "url": "https://www.amazon.es/ReleMat-SpareHome%C2%A9-Products-escotilla-lavadoras/dp/B07TY2JHS4?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:25:16.086Z"
      }
    ],
    "sourceArticles": [
      "lavadoras-carga-frontal-vs-superior-comparativa-precios-prestaciones",
      "como-comparar-precios-lavadoras-espana-guia-2026"
    ],
    "confidence": 0.05555555555555555
  },
  {
    "slug": "balay-3vs5030ia",
    "name": "Bosch Siemens Dishwasher Pump Drain Pump Pump for Balay, Neff, Constructa - No.: 611332",
    "brand": "Bosch",
    "categoryPath": [
      "electrodomesticos",
      "grandes-electrodomesticos"
    ],
    "description": "1. [![Dishwasher Drain Pump with Original Code 00631200 631200 for Bosch for Siemens - MADE IN EU - 10 Year Warranty - MONTERAL](https://m.media-amazon.com/images/I/61iwPuX1c-L._AC_SS57_.jpg)](https://www.amazon.es/-/en/Dishwasher-Original-00631200-631200-Siemens/dp/B0CZ9JV25J/ref=pd_lpo_d_sccl_2/520-3795967-8075166?pd_rd_w=13kzP&content-id=amzn1.sym.dbff13a3-ec7b-4ab4-a8ad-e4356fa2bfdb&pf_rd_p=dbff13a3-ec7b-4ab4-a8ad-e4356fa2bfdb&pf_rd_r=88DAA9VFB5CWX484VCT5&pd_rd_wg=YpvGL&pd_rd_r=b9e91a2f-1ecd",
    "specs": {
      "slug": "balay-3vs5030ia",
      "longdescription": "1. [![Dishwasher Drain Pump with Original Code 00631200 631200 for Bosch for Siemens - MADE IN EU - 10 Year Warranty - MONTERAL](https://m.media-amazon.com/images/I/61iwPuX1c-L._AC_SS57_.jpg)](https://www.amazon.es/-/en/Dishwasher-Original-00631200-631200-Siemens/dp/B0CZ9JV25J/ref=pd_lpo_d_sccl_2/520-3795967-8075166?pd_rd_w=13kzP&content-id=amzn1.sym.dbff13a3-ec7b-4ab4-a8ad-e4356fa2bfdb&pf_rd_p=dbff13a3-ec7b-4ab4-a8ad-e4356fa2bfdb&pf_rd_r=88DAA9VFB5CWX484VCT5&pd_rd_wg=YpvGL&pd_rd_r=b9e91a2f-1ecd-47f5-9213-48b29ffede0a&pd_rd_i=B0CZ9JV25J&psc=1)",
      "rating": 4.7
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.06666666666666667
    },
    "imageUrl": "https://m.media-amazon.com/images/I/61iwPuX1c-L._AC_SS57_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 33.9,
        "oldPrice": null,
        "url": "https://www.amazon.es/Bosch-Siemens-lavavajillas-drenaje-Constructa/dp/B004XL3QFS?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:25:39.231Z"
      }
    ],
    "sourceArticles": [
      "lavavajillas-integrables-vs-libre-instalacion-comparativa-2026"
    ],
    "confidence": 0.06666666666666667
  },
  {
    "slug": "beko-hic64402t",
    "name": "Beko FBE69100X – Freestanding Cooker 60 x 60 cm, Induction Hob 4 Zones, Multifunction Oven 72 L, Class A, Rustless, HidroClean",
    "brand": "Beko",
    "categoryPath": [
      "electrodomesticos",
      "grandes-electrodomesticos"
    ],
    "description": "Beko FBE69100X – Freestanding Cooker 60 x 60 cm, Induction Hob 4 Zones, Multifunction Oven 72 L, Class A, Rustless, HidroClean — Vitrocerámica: cuándo encaja (referenced in placas-induccion-vs-vitroceramica-vs-gas-comparativa-precios-consumo)",
    "specs": {
      "slug": "beko-hic64402t",
      "rating": 4.8,
      "reviewcount": 0
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.0625
    },
    "imageUrl": "https://m.media-amazon.com/images/I/31Idm0gcB3L._AC_SR38,50_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 212.07,
        "oldPrice": null,
        "url": "https://www.amazon.es/Beko-FBE69100X-instalaci%C3%B3n-multifunci%C3%B3n-inoxidable/dp/B0FV39BNHM?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:25:49.990Z"
      }
    ],
    "sourceArticles": [
      "placas-induccion-vs-vitroceramica-vs-gas-comparativa-precios-consumo"
    ],
    "confidence": 0.0625
  },
  {
    "slug": "beper-raf200",
    "name": "Beper BP.304 Electric Blender and Mixer, 150 W, ABS, Chromed Steel, White Dove Grey",
    "brand": "Beper",
    "categoryPath": [
      "electrodomesticos",
      "climatizacion"
    ],
    "description": "Beper BP.304 Electric Blender and Mixer, 150 W, ABS, Chromed Steel, White Dove Grey — Beper P206RAF200 (referenced in mejores-climatizadores-evaporativos-2026)",
    "specs": {
      "slug": "beper-raf200",
      "rating": 4.6,
      "reviewcount": 1332
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.06666666666666667
    },
    "imageUrl": "https://m.media-amazon.com/images/I/51WGbwH1CSL._AC_SS115_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 53.71,
        "oldPrice": null,
        "url": "https://www.amazon.es/Beper-BP-304-Batidora-150-W/dp/B07SSLRCT6?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:25:36.225Z"
      }
    ],
    "sourceArticles": [
      "mejores-climatizadores-evaporativos-2026"
    ],
    "confidence": 0.06666666666666667
  },
  {
    "slug": "bosch-dul62fa21",
    "name": "Bosch Serie 2 DUL62FA21 – Hood (250 m³/h, Ducted, E, E, D, 68 dB)",
    "brand": "Bosch",
    "categoryPath": [
      "electrodomesticos",
      "grandes-electrodomesticos"
    ],
    "description": "[![The perfect last-minute gift](https://m.media-amazon.com/images/I/21j1PbMZccL.png)](https://www.amazon.es/-/en/b/ref=ES_Org_GC_DP_Multi_ILM_Evergreen?_encoding=UTF8&node=3564279031&pd_rd_w=VdxyC&content-id=amzn1.sym.b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_p=b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_r=K3YADJMD39ZE51HWGMAV&pd_rd_wg=pQdav&pd_rd_r=1f506e5c-2e46-474a-91ec-5945a088c861)",
    "specs": {
      "slug": "bosch-dul62fa21",
      "longdescription": "[![The perfect last-minute gift](https://m.media-amazon.com/images/I/21j1PbMZccL.png)](https://www.amazon.es/-/en/b/ref=ES_Org_GC_DP_Multi_ILM_Evergreen?_encoding=UTF8&node=3564279031&pd_rd_w=VdxyC&content-id=amzn1.sym.b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_p=b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_r=K3YADJMD39ZE51HWGMAV&pd_rd_wg=pQdav&pd_rd_r=1f506e5c-2e46-474a-91ec-5945a088c861)",
      "rating": 4.3
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.2222222222222222
    },
    "imageUrl": "https://m.media-amazon.com/images/I/71qhjbawn+L._AC_SS57_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 98.35,
        "oldPrice": null,
        "url": "https://www.amazon.es/Bosch-Serie-DUL62FA21-Campana-Canalizado/dp/B07JGYS6HP?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:25:38.807Z"
      }
    ],
    "sourceArticles": [
      "campanas-extractoras-decorativas-vs-telescopicas-comparativa-2026"
    ],
    "confidence": 0.2222222222222222
  },
  {
    "slug": "bosch-hbg7341b1",
    "name": "Bosch HBG7341B1 Series 8 Smart Built-In Oven, 60 x 60 cm, Made in Germany, Black, Stain and Self-Cleaning, Air Fry, Bosch Assist Automatic, 3D Hot Air, Touch Screen A",
    "brand": "Bosch",
    "categoryPath": [
      "electrodomesticos",
      "grandes-electrodomesticos"
    ],
    "description": "- [Large Appliances](https://www.amazon.es/-/en/b/ref=dp_bc_1?ie=UTF8&node=4772050031)\n- ›\n- [Ovens & Hobs](https://www.amazon.es/b/ref=dp_bc_2?ie=UTF8&node=14565171031)\n- ›\n- [Installed Ovens](https://www.amazon.es/-/en/b/ref=dp_bc_3?ie=UTF8&node=14565217031)",
    "specs": {
      "slug": "bosch-hbg7341b1",
      "longdescription": "- [Large Appliances](https://www.amazon.es/-/en/b/ref=dp_bc_1?ie=UTF8&node=4772050031)\n- ›\n- [Ovens & Hobs](https://www.amazon.es/b/ref=dp_bc_2?ie=UTF8&node=14565171031)\n- ›\n- [Installed Ovens](https://www.amazon.es/-/en/b/ref=dp_bc_3?ie=UTF8&node=14565217031)",
      "rating": 4.5
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.08333333333333333
    },
    "imageUrl": "https://m.media-amazon.com/images/I/31b2aDIjfjL._AC_SR38,50_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 263.64,
        "oldPrice": null,
        "url": "https://www.amazon.es/Bosch-Serie-HBG7341B1-horno-el%C3%A9ctrico/dp/B0CK9GGMTP?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:21:29.151Z"
      }
    ],
    "sourceArticles": [
      "top-10-hornos-piroliticos-calidad-precio-2026"
    ],
    "confidence": 0.08333333333333333
  },
  {
    "slug": "bosch-pue611bb5e",
    "name": "BOSCH PVS651FC5E INDUCTION TOP",
    "brand": "BOSCH",
    "categoryPath": [
      "electrodomesticos",
      "grandes-electrodomesticos"
    ],
    "description": "BOSCH PVS651FC5E INDUCTION TOP — Inducción: cuándo encaja (referenced in placas-induccion-vs-vitroceramica-vs-gas-comparativa-precios-consumo)",
    "specs": {
      "slug": "bosch-pue611bb5e",
      "rating": 4.3,
      "reviewcount": 54
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.125
    },
    "imageUrl": "https://m.media-amazon.com/images/I/51hqGDbgCoL._AC_SS115_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 184.41,
        "oldPrice": null,
        "url": "https://www.amazon.es/BOSCH-PVS651FC5E-ENCIMERA-POR-INDUCCION/dp/B07SK258C2?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:21:30.526Z"
      }
    ],
    "sourceArticles": [
      "placas-induccion-vs-vitroceramica-vs-gas-comparativa-precios-consumo"
    ],
    "confidence": 0.125
  },
  {
    "slug": "bosch-sms2hvi67e",
    "name": "Bosch SMU6ZCS16E Series 6 Undermount Dishwasher, PerfectDry, Home Connect, Remote Diagnosis, Extra Clean Zone, Steel, 60 cm",
    "brand": "Bosch",
    "categoryPath": [
      "electrodomesticos",
      "grandes-electrodomesticos"
    ],
    "description": "[![The perfect last-minute gift](https://m.media-amazon.com/images/I/21j1PbMZccL.png)](https://www.amazon.es/-/en/b/ref=ES_Org_GC_DP_Multi_ILM_Evergreen?_encoding=UTF8&node=3564279031&pd_rd_w=5REMq&content-id=amzn1.sym.b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_p=b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_r=7A3T2K3Z49G5G5CWVS93&pd_rd_wg=felQH&pd_rd_r=660ff986-a777-4251-a5cb-4b94667e4703)",
    "specs": {
      "slug": "bosch-sms2hvi67e",
      "longdescription": "[![The perfect last-minute gift](https://m.media-amazon.com/images/I/21j1PbMZccL.png)](https://www.amazon.es/-/en/b/ref=ES_Org_GC_DP_Multi_ILM_Evergreen?_encoding=UTF8&node=3564279031&pd_rd_w=5REMq&content-id=amzn1.sym.b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_p=b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_r=7A3T2K3Z49G5G5CWVS93&pd_rd_wg=felQH&pd_rd_r=660ff986-a777-4251-a5cb-4b94667e4703)",
      "rating": 4.4
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.05
    },
    "imageUrl": "https://m.media-amazon.com/images/I/41KfPlQVSML._AC_SR38,50_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 114.88,
        "oldPrice": null,
        "url": "https://www.amazon.es/BOSCH-SMU6ZCS16E-Lavavajillas-inteligente-inoxidable/dp/B0CGRMFJ7X?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:26:05.697Z"
      }
    ],
    "sourceArticles": [
      "lavavajillas-integrables-vs-libre-instalacion-comparativa-2026"
    ],
    "confidence": 0.05
  },
  {
    "slug": "bosch-wan24267es",
    "name": "LICHTBLAU Metal Door Hinge 153150 for Bosch Siemens Porthole Washing Machine 163128, 066792, 285049, 285049",
    "brand": "LICHTBLAU",
    "categoryPath": [
      "electrodomesticos",
      "grandes-electrodomesticos"
    ],
    "description": "[![The perfect last-minute gift](https://m.media-amazon.com/images/I/21j1PbMZccL.png)](https://www.amazon.es/-/en/b/ref=ES_Org_GC_DP_Multi_ILM_Evergreen?_encoding=UTF8&node=3564279031&pd_rd_w=YX3Vd&content-id=amzn1.sym.b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_p=b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_r=VSCVGC07E3SM3Y8W84GB&pd_rd_wg=9pCiS&pd_rd_r=92427418-586f-440f-9f9d-6a6d52d77b50)",
    "specs": {
      "slug": "bosch-wan24267es",
      "longdescription": "[![The perfect last-minute gift](https://m.media-amazon.com/images/I/21j1PbMZccL.png)](https://www.amazon.es/-/en/b/ref=ES_Org_GC_DP_Multi_ILM_Evergreen?_encoding=UTF8&node=3564279031&pd_rd_w=YX3Vd&content-id=amzn1.sym.b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_p=b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_r=VSCVGC07E3SM3Y8W84GB&pd_rd_wg=9pCiS&pd_rd_r=92427418-586f-440f-9f9d-6a6d52d77b50)",
      "rating": 4.5,
      "reviewcount": 574
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.05
    },
    "imageUrl": "https://m.media-amazon.com/images/I/41UmxcCLBNL._AC_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 160,
        "oldPrice": null,
        "url": "https://www.amazon.es/LICHTBLAU-Bisagra-puerta-Siemens-lavadora/dp/B0F196FYVT?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:25:53.834Z"
      }
    ],
    "sourceArticles": [
      "lavadoras-carga-frontal-vs-superior-comparativa-precios-prestaciones"
    ],
    "confidence": 0.05
  },
  {
    "slug": "cata-is-6021-bk",
    "name": "CATA Model LCI 6031 | Butane Gas Hobs 4 Fire | Gas Cooker | Width 64 cm | Cast Iron Grills/Burners | Power 9.2 kW",
    "brand": "CATA",
    "categoryPath": [
      "electrodomesticos",
      "grandes-electrodomesticos"
    ],
    "description": "CATA Model LCI 6031 | Butane Gas Hobs 4 Fire | Gas Cooker | Width 64 cm | Cast Iron Grills/Burners | Power 9.2 kW — Gas: cuándo encaja (referenced in placas-induccion-vs-vitroceramica-vs-gas-comparativa-precios-consumo)",
    "specs": {
      "slug": "cata-is-6021-bk",
      "rating": 3.8
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.1111111111111111
    },
    "imageUrl": "https://m.media-amazon.com/images/I/61jcd-dW7zS._AC_SS115_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 280.99,
        "oldPrice": null,
        "url": "https://www.amazon.es/Encimeras-Parrillas-Quemadores-fundido-potencia/dp/B00E6C1MCS?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:21:35.760Z"
      }
    ],
    "sourceArticles": [
      "placas-induccion-vs-vitroceramica-vs-gas-comparativa-precios-consumo"
    ],
    "confidence": 0.1111111111111111
  },
  {
    "slug": "cata-tf-5260",
    "name": "CATA | extractor hood | TF 2003 model DURALUM 60 | 2 extraction speeds | cooker hood 390m3/h - 150m3/h | Stainless steel finish",
    "brand": "CATA",
    "categoryPath": [
      "electrodomesticos",
      "grandes-electrodomesticos"
    ],
    "description": "CATA | extractor hood | TF 2003 model DURALUM 60 | 2 extraction speeds | cooker hood 390m3/h - 150m3/h | Stainless steel finish — Telescópicas (integradas en mueble) (referenced in campanas-extractoras-decorativas-vs-telescopicas-comparativa-2026)",
    "specs": {
      "slug": "cata-tf-5260",
      "rating": 3.8,
      "reviewcount": 980
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.05555555555555555
    },
    "imageUrl": "https://m.media-amazon.com/images/I/61fJ-HKXwvL._AC_SS115_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 128.1,
        "oldPrice": null,
        "url": "https://www.amazon.es/CATA-2003-DURALUM-Integrado-Canalizado/dp/B00WI32CC6?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:21:36.231Z"
      }
    ],
    "sourceArticles": [
      "campanas-extractoras-decorativas-vs-telescopicas-comparativa-2026"
    ],
    "confidence": 0.05555555555555555
  },
  {
    "slug": "cecotec-bigdry-4000-expert",
    "name": "Cecotec Dehumidifier Big Dry 4000 Expert Connected. Wifi Control, 10L/day, Removable tank 2.5L, Coverage 105m3/h, Gas R290, Quiet, Humidity 40% to 80%, LED Display, Auto Shut-off",
    "brand": "Cecotec",
    "categoryPath": [
      "electrodomesticos",
      "climatizacion"
    ],
    "description": "Cecotec Dehumidifier Big Dry 4000 Expert Connected. Wifi Control, 10L/day, Removable tank 2.5L, Coverage 105m3/h, Gas R290, Quiet, Humidity 40% to 80%, LED Display, Auto Shut-off — Cecotec BigDry 4000 Expert (referenced in top-10-deshumidificadores-calidad-precio-2026)",
    "specs": {
      "slug": "cecotec-bigdry-4000-expert",
      "rating": 4.4,
      "reviewcount": 1157
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.12
    },
    "imageUrl": "https://m.media-amazon.com/images/I/51+1JJGIwRL._AC_SS115_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 68.29,
        "oldPrice": null,
        "url": "https://www.amazon.es/Cecotec-Deshumidificador-extra%C3%ADble-Silencioso-Temporizador/dp/B095HJY2JJ?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:21:36.388Z"
      }
    ],
    "sourceArticles": [
      "top-10-deshumidificadores-calidad-precio-2026"
    ],
    "confidence": 0.12
  },
  {
    "slug": "cecotec-bigdry-9000",
    "name": "Cecotec Dehumidifier Big Dry 9000 Professional Connected. Timer 12h, 20L/day, Removable tank 4.5L, Coverage 250 m3/h, Gas R290, Quiet, Humidity Adjustment, Wifi Control",
    "brand": "Cecotec",
    "categoryPath": [
      "electrodomesticos",
      "climatizacion"
    ],
    "description": "[![The perfect last-minute gift](https://m.media-amazon.com/images/I/21j1PbMZccL.png)](https://www.amazon.es/-/en/b/ref=ES_Org_GC_DP_Multi_ILM_Evergreen?_encoding=UTF8&node=3564279031&pd_rd_w=nk4z0&content-id=amzn1.sym.b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_p=b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_r=YNJPN74ASWABENX6MX15&pd_rd_wg=FSV9L&pd_rd_r=9f51150c-98c1-46a3-a65c-bd12808ae3c9)",
    "specs": {
      "slug": "cecotec-bigdry-9000",
      "longdescription": "[![The perfect last-minute gift](https://m.media-amazon.com/images/I/21j1PbMZccL.png)](https://www.amazon.es/-/en/b/ref=ES_Org_GC_DP_Multi_ILM_Evergreen?_encoding=UTF8&node=3564279031&pd_rd_w=nk4z0&content-id=amzn1.sym.b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_p=b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_r=YNJPN74ASWABENX6MX15&pd_rd_wg=FSV9L&pd_rd_r=9f51150c-98c1-46a3-a65c-bd12808ae3c9)",
      "rating": 4.4
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.08695652173913043
    },
    "imageUrl": "https://m.media-amazon.com/images/I/51V+ihsKluL._AC_SY300_SX300_QL70_ML2_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 61.34,
        "oldPrice": null,
        "url": "https://www.amazon.es/Cecotec-Deshumidificador-Professional-Connected-Temporizador/dp/B095KMPLLN?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:21:37.172Z"
      }
    ],
    "sourceArticles": [
      "top-10-deshumidificadores-calidad-precio-2026"
    ],
    "confidence": 0.08695652173913043
  },
  {
    "slug": "cecotec-conga-11090",
    "name": "Cecotec Conga 11090 Spin Revolution Home&Wash Robot Vacuum Cleaner + Automatic Empty Station",
    "brand": "Cecotec",
    "categoryPath": [
      "electrodomesticos",
      "grandes-electrodomesticos"
    ],
    "description": "[![The perfect last-minute gift](https://m.media-amazon.com/images/I/21j1PbMZccL.png)](https://www.amazon.es/-/en/b/ref=ES_Org_GC_DP_Multi_ILM_Evergreen?_encoding=UTF8&node=3564279031&pd_rd_w=vig6R&content-id=amzn1.sym.b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_p=b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_r=M0C68AC21NPFM1CMYF9K&pd_rd_wg=zFOhY&pd_rd_r=d630ea1d-9221-46f8-8df7-aced07288532)",
    "specs": {
      "slug": "cecotec-conga-11090",
      "longdescription": "[![The perfect last-minute gift](https://m.media-amazon.com/images/I/21j1PbMZccL.png)](https://www.amazon.es/-/en/b/ref=ES_Org_GC_DP_Multi_ILM_Evergreen?_encoding=UTF8&node=3564279031&pd_rd_w=vig6R&content-id=amzn1.sym.b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_p=b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_r=M0C68AC21NPFM1CMYF9K&pd_rd_wg=zFOhY&pd_rd_r=d630ea1d-9221-46f8-8df7-aced07288532)",
      "rating": 2.8,
      "reviewcount": 657
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.2
    },
    "imageUrl": "https://m.media-amazon.com/images/I/81VbQpTAzsL._AC_SS57_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 399,
        "oldPrice": null,
        "url": "https://www.amazon.es/Cecotec-Friegasuelos-Autovaciado-Autolimpieza-Ultras%C3%B3nica/dp/B0BQ23K5W2?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:21:40.825Z"
      }
    ],
    "sourceArticles": [
      "como-comparar-precios-pequeno-electrodomestico-2026"
    ],
    "confidence": 0.2
  },
  {
    "slug": "cecotec-conga-7090",
    "name": "Cecotec Robot Aspirador y Friegasuelos Conga 7090 IA. Inteligencia Artificial y Láser, 4 en 1, 10000 Pa, Tecnología Ciclónica, App, Reconoce Objetos, Estancias, Suelos y Mascotas, Roomplan 3.0",
    "brand": "Cecotec",
    "categoryPath": [
      "electrodomesticos",
      "grandes-electrodomesticos"
    ],
    "description": "[![Free delivery on first orders message](https://m.media-amazon.com/images/I/31pWJ-XZqeL.jpg)](https://www.amazon.es/-/en/b/?_encoding=UTF8&node=18978330031&pd_rd_w=GEhYA&content-id=amzn1.sym.57bf98f3-83ad-485b-88b5-01efff37ea63&pf_rd_p=57bf98f3-83ad-485b-88b5-01efff37ea63&pf_rd_r=K2CNB8JVM85Y0ZF88GJ6&pd_rd_wg=9RHw8&pd_rd_r=dd6e5f25-dd6d-4aae-a7f3-101a93900d8f)",
    "specs": {
      "slug": "cecotec-conga-7090",
      "longdescription": "[![Free delivery on first orders message](https://m.media-amazon.com/images/I/31pWJ-XZqeL.jpg)](https://www.amazon.es/-/en/b/?_encoding=UTF8&node=18978330031&pd_rd_w=GEhYA&content-id=amzn1.sym.57bf98f3-83ad-485b-88b5-01efff37ea63&pf_rd_p=57bf98f3-83ad-485b-88b5-01efff37ea63&pf_rd_r=K2CNB8JVM85Y0ZF88GJ6&pd_rd_wg=9RHw8&pd_rd_r=dd6e5f25-dd6d-4aae-a7f3-101a93900d8f)",
      "rating": 4
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.13043478260869565
    },
    "imageUrl": "https://m.media-amazon.com/images/I/61fQpURVVoL._AC_SY300_SX300_QL70_ML2_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 280.17,
        "oldPrice": null,
        "url": "https://www.amazon.es/Cecotec-fregasuelos-Conga-7090-Inteligencia/dp/B08M5L9Y8X?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:21:40.920Z"
      }
    ],
    "sourceArticles": [
      "mejores-aspiradores-robot-con-mopa-2026",
      "historico-precios-importancia-comprar-muebles-electrodomesticos-2026"
    ],
    "confidence": 0.13043478260869565
  },
  {
    "slug": "cecotec-conga-8290",
    "name": "Cecotec Robot Aspirador con Navegación Láser y App Conga 8290 Immortal Ultra Power Genesis. 4 en 1, 7000Pa, Autonomía 280mins, Mopa de Fregado, Cepillo Lateral, 3 Niveles de Potencia y de Fregado",
    "brand": "Cecotec",
    "categoryPath": [
      "electrodomesticos",
      "grandes-electrodomesticos"
    ],
    "description": "1. [![Cecotec Robot Aspirador Conga 8490 Ultimate Ultra Power, Navegación Láser, APP Limpieza 4 en 1, Barre, Aspira, Friega y Pasa ](https://m.media-amazon.com/images/I/81A+D-OxDiL._AC_SS57_.jpg)](https://www.amazon.es/-/en/Cecotec-Aspirador-Ultimate-Navegaci%C3%B3n-Autonom%C3%ADa/dp/B0DHKHY5R4/ref=pd_lpo_d_sccl_1/520-5538149-9926220?pd_rd_w=5qyYh&content-id=amzn1.sym.dbff13a3-ec7b-4ab4-a8ad-e4356fa2bfdb&pf_rd_p=dbff13a3-ec7b-4ab4-a8ad-e4356fa2bfdb&pf_rd_r=H6V58T4K6P0CH2MWRS0G&pd_rd_wg=9deYY&pd_",
    "specs": {
      "slug": "cecotec-conga-8290",
      "longdescription": "1. [![Cecotec Robot Aspirador Conga 8490 Ultimate Ultra Power, Navegación Láser, APP Limpieza 4 en 1, Barre, Aspira, Friega y Pasa ](https://m.media-amazon.com/images/I/81A+D-OxDiL._AC_SS57_.jpg)](https://www.amazon.es/-/en/Cecotec-Aspirador-Ultimate-Navegaci%C3%B3n-Autonom%C3%ADa/dp/B0DHKHY5R4/ref=pd_lpo_d_sccl_1/520-5538149-9926220?pd_rd_w=5qyYh&content-id=amzn1.sym.dbff13a3-ec7b-4ab4-a8ad-e4356fa2bfdb&pf_rd_p=dbff13a3-ec7b-4ab4-a8ad-e4356fa2bfdb&pf_rd_r=H6V58T4K6P0CH2MWRS0G&pd_rd_wg=9deYY&pd_rd_r=80a46822-0e55-4dc8-acd5-c515ec82ca00&pd_rd_i=B0DHKHY5R4&psc=1)",
      "rating": 3.9
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.13636363636363635
    },
    "imageUrl": "https://m.media-amazon.com/images/I/81A+D-OxDiL._AC_SS57_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 139.67,
        "oldPrice": null,
        "url": "https://www.amazon.es/Cecotec-Aspirador-Navegaci%C3%B3n-Immortal-Autonom%C3%ADa/dp/B0BQ1VS6FN?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:21:43.040Z"
      }
    ],
    "sourceArticles": [
      "mejores-aspiradores-robot-con-mopa-2026"
    ],
    "confidence": 0.13636363636363635
  },
  {
    "slug": "cecotec-conga-rockstar-700",
    "name": "Cecotec Conga Rockstar 880 X-Treme ErgoFlex Cordless Broom Vacuum Cleaner, 3 in 1, Brushless Digital Motor, 480 W and 30 kPa, Autonomy 100 min, 3 Programs, Jalisco Brush and Flexible Tube",
    "brand": "Cecotec",
    "categoryPath": [
      "electrodomesticos",
      "grandes-electrodomesticos"
    ],
    "description": "Cecotec Conga Rockstar 880 X-Treme ErgoFlex Cordless Broom Vacuum Cleaner, 3 in 1, Brushless Digital Motor, 480 W and 30 kPa, Autonomy 100 min, 3 Programs, Jalisco Brush and Flexible Tube — Aspirador escoba: cuándo encaja (referenced in como-comparar-aspirador-escoba-vs-robot-guia-2026)",
    "specs": {
      "slug": "cecotec-conga-rockstar-700",
      "rating": 3.9,
      "reviewcount": 657
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.10344827586206896
    },
    "imageUrl": "https://m.media-amazon.com/images/I/51Er0vQKm9L._AC_SX522_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 74.3,
        "oldPrice": null,
        "url": "https://www.amazon.es/Cecotec-Aspirador-ErgoFlex-Brushless-Autonom%C3%ADa/dp/B0B46WQ86Q?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:21:44.492Z"
      }
    ],
    "sourceArticles": [
      "como-comparar-aspirador-escoba-vs-robot-guia-2026"
    ],
    "confidence": 0.10344827586206896
  },
  {
    "slug": "cecotec-energysilence-5500-pure-tech",
    "name": "Cecotec EnergySilence PureTech 5500 Portable Evaporative Cold Air Conditioner, 80 W, 3 in 1: Cold, Ionizer and Fan, 12 L, 3 Speeds, Remote Control, LCD Display, Air Flow 500 m3/h",
    "brand": "Cecotec",
    "categoryPath": [
      "electrodomesticos",
      "climatizacion"
    ],
    "description": "Cecotec EnergySilence PureTech 5500 Portable Evaporative Cold Air Conditioner, 80 W, 3 in 1: Cold, Ionizer and Fan, 12 L, 3 Speeds, Remote Control, LCD Display, Air Flow 500 m3/h — Cecotec EnergySilence 5500 Pure Tech (referenced in mejores-climatizadores-evaporativos-2026)",
    "specs": {
      "slug": "cecotec-energysilence-5500-pure-tech",
      "rating": 3.5,
      "reviewcount": 154
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.14285714285714285
    },
    "imageUrl": "https://m.media-amazon.com/images/I/51Xc4l4fI8L._AC_SS115_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 215.64,
        "oldPrice": null,
        "url": "https://www.amazon.es/Cecotec-Climatizador-Evaporativo-Port%C3%A1til-EnergySilence/dp/B0BYP1YXY7?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:21:45.694Z"
      }
    ],
    "sourceArticles": [
      "mejores-climatizadores-evaporativos-2026"
    ],
    "confidence": 0.14285714285714285
  },
  {
    "slug": "cecotec-energysilence-aero-3600",
    "name": "Cecotec EnergySilence 3600 Vision Sky Ceiling Fan, 50 W, Diameter 92 cm, Lamp, 3 Speeds, 6 Reversible Blades, Summer/Winter Function, Chain Switch, White/Blue",
    "brand": "Cecotec",
    "categoryPath": [
      "electrodomesticos",
      "climatizacion"
    ],
    "description": "[![Free delivery on first orders message](https://m.media-amazon.com/images/I/31pWJ-XZqeL.jpg)](https://www.amazon.es/-/en/b/?_encoding=UTF8&node=18978330031&pd_rd_w=yDmYl&content-id=amzn1.sym.57bf98f3-83ad-485b-88b5-01efff37ea63&pf_rd_p=57bf98f3-83ad-485b-88b5-01efff37ea63&pf_rd_r=9KVAJWY3V9VM9X8PMSQH&pd_rd_wg=wGEUR&pd_rd_r=b18edd5c-df54-4414-a602-edf0b043dfc0)",
    "specs": {
      "slug": "cecotec-energysilence-aero-3600",
      "longdescription": "[![Free delivery on first orders message](https://m.media-amazon.com/images/I/31pWJ-XZqeL.jpg)](https://www.amazon.es/-/en/b/?_encoding=UTF8&node=18978330031&pd_rd_w=yDmYl&content-id=amzn1.sym.57bf98f3-83ad-485b-88b5-01efff37ea63&pf_rd_p=57bf98f3-83ad-485b-88b5-01efff37ea63&pf_rd_r=9KVAJWY3V9VM9X8PMSQH&pd_rd_wg=wGEUR&pd_rd_r=b18edd5c-df54-4414-a602-edf0b043dfc0)",
      "rating": 4.3
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.13636363636363635
    },
    "imageUrl": "https://m.media-amazon.com/images/I/41VLRGzdD7L._AC_SS57_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 37.11,
        "oldPrice": null,
        "url": "https://www.amazon.es/Cecotec-EnergySilence-Velocidades-reversibles-Interruptor/dp/B09478VFYY?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:21:47.669Z"
      }
    ],
    "sourceArticles": [
      "ventiladores-techo-vs-torre-vs-columna-comparativa-2026"
    ],
    "confidence": 0.13636363636363635
  },
  {
    "slug": "cecotec-energysilence-aero-4250-columna",
    "name": "Cecotec EnergySilence Aero 550 Ceiling Fan with Remote Control, Timer and LED Light, 60 W, Diameter 132 cm, 3 Blades, 3 Speeds, Winter Function, White Design",
    "brand": "Cecotec",
    "categoryPath": [
      "electrodomesticos",
      "climatizacion"
    ],
    "description": "1. [![Cecotec EnergySilence Aero 5230 WhiteWood Ceiling Fan with Light and Remote Control, 52 Inches, 40 W DC Motor, 3 Blades, LED ](https://m.media-amazon.com/images/I/513kTJh4zML._AC_SS57_.jpg)](https://www.amazon.es/-/en/Cecotec-EnergySilence-WhiteWood-Ceiling-Adjustable/dp/B0G7518B1T/ref=pd_lpo_d_sccl_1/521-9596330-7042343?pd_rd_w=ZLVjL&content-id=amzn1.sym.dbff13a3-ec7b-4ab4-a8ad-e4356fa2bfdb&pf_rd_p=dbff13a3-ec7b-4ab4-a8ad-e4356fa2bfdb&pf_rd_r=9NKCX0PQPDJJ79JJ2DPB&pd_rd_wg=OAJvz&pd_rd_r=eb",
    "specs": {
      "slug": "cecotec-energysilence-aero-4250-columna",
      "longdescription": "1. [![Cecotec EnergySilence Aero 5230 WhiteWood Ceiling Fan with Light and Remote Control, 52 Inches, 40 W DC Motor, 3 Blades, LED ](https://m.media-amazon.com/images/I/513kTJh4zML._AC_SS57_.jpg)](https://www.amazon.es/-/en/Cecotec-EnergySilence-WhiteWood-Ceiling-Adjustable/dp/B0G7518B1T/ref=pd_lpo_d_sccl_1/521-9596330-7042343?pd_rd_w=ZLVjL&content-id=amzn1.sym.dbff13a3-ec7b-4ab4-a8ad-e4356fa2bfdb&pf_rd_p=dbff13a3-ec7b-4ab4-a8ad-e4356fa2bfdb&pf_rd_r=9NKCX0PQPDJJ79JJ2DPB&pd_rd_wg=OAJvz&pd_rd_r=eb9d8fc0-e766-4d56-80e1-c5f61d693222&pd_rd_i=B0G7518B1T&psc=1)",
      "rating": 4.1
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.12
    },
    "imageUrl": "https://m.media-amazon.com/images/I/513kTJh4zML._AC_SS57_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 82.56,
        "oldPrice": null,
        "url": "https://www.amazon.es/Cecotec-Ventilador-Temporizador-EnergySilence-Velocidades/dp/B0913KQNX6?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:21:46.087Z"
      }
    ],
    "sourceArticles": [
      "ventiladores-techo-vs-torre-vs-columna-comparativa-2026"
    ],
    "confidence": 0.12
  },
  {
    "slug": "cecotec-energysilence-aero-4250-dc-fresh",
    "name": "Cecotec EnergySilence Aero 4250 DC Cool Ceiling Fan with Light, 40 W, DC Motor, Diameter 42\" with 4 Reversible Blades, LED Light, Remote Control, Timer, 6 Speeds",
    "brand": "Cecotec",
    "categoryPath": [
      "electrodomesticos",
      "climatizacion"
    ],
    "description": "Cecotec EnergySilence Aero 4250 DC Cool Ceiling Fan with Light, 40 W, DC Motor, Diameter 42\" with 4 Reversible Blades, LED Light, Remote Control, Timer, 6 Speeds — Modelos destacados (referenced in ventiladores-techo-vs-torre-vs-columna-comparativa-2026)",
    "specs": {
      "slug": "cecotec-energysilence-aero-4250-dc-fresh",
      "rating": 4.2,
      "reviewcount": 890
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.19047619047619047
    },
    "imageUrl": "https://m.media-amazon.com/images/I/41UR4M10cSL._AC_SS115_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 66.03,
        "oldPrice": null,
        "url": "https://www.amazon.es/Cecotec-EnergySilence-Reversibles-Temporizador-Velocidades/dp/B0BQ1R9CJK?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:21:53.823Z"
      }
    ],
    "sourceArticles": [
      "ventiladores-techo-vs-torre-vs-columna-comparativa-2026"
    ],
    "confidence": 0.19047619047619047
  },
  {
    "slug": "cecotec-forceclima-7100-sound",
    "name": "Cecotec ForceClima 7100 Portable Air Conditioner with Remote Control, 7000 BTU, Low Consumption, LED Display, 4 Modes, 2 Speed, Coverage 15-20 m²",
    "brand": "Cecotec",
    "categoryPath": [
      "electrodomesticos",
      "climatizacion"
    ],
    "description": "Cecotec ForceClima 7100 Portable Air Conditioner with Remote Control, 7000 BTU, Low Consumption, LED Display, 4 Modes, 2 Speed, Coverage 15-20 m² — Aire acondicionado portátil: cuándo encaja (referenced in climatizadores-evaporativos-vs-aire-portatil-comparativa-2026)",
    "specs": {
      "slug": "cecotec-forceclima-7100-sound",
      "rating": 4.2,
      "reviewcount": 2066
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.1111111111111111
    },
    "imageUrl": "https://m.media-amazon.com/images/I/71yLX8e86jL._AC_SX466_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 100,
        "oldPrice": null,
        "url": "https://www.amazon.es/Cecotec-Acondicionado-ForceClima-Soundless-Velocidades/dp/B0BPZHKY25?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:21:50.846Z"
      }
    ],
    "sourceArticles": [
      "climatizadores-evaporativos-vs-aire-portatil-comparativa-2026",
      "comparador-electrodomesticos-verano-aire-ventilacion-2026"
    ],
    "confidence": 0.1111111111111111
  },
  {
    "slug": "cecotec-forceclima-9750",
    "name": "Cecotec ForceClima 9150 Style Portable Air Conditioner with Remote Control, 9000 BTU, Touch Control, LED Display, 4 Modes, 2 Speeds, Dehumidifier Mode, Timer, 25 m²",
    "brand": "Cecotec",
    "categoryPath": [
      "electrodomesticos",
      "climatizacion"
    ],
    "description": "[![The perfect last-minute gift](https://m.media-amazon.com/images/I/21j1PbMZccL.png)](https://www.amazon.es/-/en/b/ref=ES_Org_GC_DP_Multi_ILM_Evergreen?_encoding=UTF8&node=3564279031&pd_rd_w=IEZaO&content-id=amzn1.sym.b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_p=b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_r=M1QYWTFXJ7JMXNZ1X8WB&pd_rd_wg=KQQTj&pd_rd_r=8713af8e-d182-427c-bacb-7a771f0fa2d9)",
    "specs": {
      "slug": "cecotec-forceclima-9750",
      "longdescription": "[![The perfect last-minute gift](https://m.media-amazon.com/images/I/21j1PbMZccL.png)](https://www.amazon.es/-/en/b/ref=ES_Org_GC_DP_Multi_ILM_Evergreen?_encoding=UTF8&node=3564279031&pd_rd_w=IEZaO&content-id=amzn1.sym.b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_p=b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_r=M1QYWTFXJ7JMXNZ1X8WB&pd_rd_wg=KQQTj&pd_rd_r=8713af8e-d182-427c-bacb-7a771f0fa2d9)",
      "rating": 4.2,
      "reviewcount": 166
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.06666666666666667
    },
    "imageUrl": "https://m.media-amazon.com/images/I/4114Lp-hufL._AC_SX679_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 22.23,
        "oldPrice": null,
        "url": "https://www.amazon.es/Cecotec-Acondicionado-Velocidades-Deshumidificador-Temporizador/dp/B0BPZRG11F?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:26:29.150Z"
      }
    ],
    "sourceArticles": [
      "como-comparar-precios-aire-acondicionado-portatil-espana-2026"
    ],
    "confidence": 0.06666666666666667
  },
  {
    "slug": "cecotec-forcesilence-590-skyline",
    "name": "Cecotec Ventilador de Torre EnergySilence 690 Skyline de 29\", 50 W de potencia, De pie, 3 Modos y 3 Velocidades, Temporizador 8h, Oscilación 90º.",
    "brand": "Cecotec",
    "categoryPath": [
      "electrodomesticos",
      "climatizacion"
    ],
    "description": "[![The perfect last-minute gift](https://m.media-amazon.com/images/I/21j1PbMZccL.png)](https://www.amazon.es/-/en/b/ref=ES_Org_GC_DP_Multi_ILM_Evergreen?_encoding=UTF8&node=3564279031&pd_rd_w=7H0Eo&content-id=amzn1.sym.b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_p=b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_r=D1QC4MQHBX7DEPVN2HP6&pd_rd_wg=XMlyt&pd_rd_r=3085ead3-b5f5-4866-acf2-4319fd5e8fff)",
    "specs": {
      "slug": "cecotec-forcesilence-590-skyline",
      "longdescription": "[![The perfect last-minute gift](https://m.media-amazon.com/images/I/21j1PbMZccL.png)](https://www.amazon.es/-/en/b/ref=ES_Org_GC_DP_Multi_ILM_Evergreen?_encoding=UTF8&node=3564279031&pd_rd_w=7H0Eo&content-id=amzn1.sym.b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_p=b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_r=D1QC4MQHBX7DEPVN2HP6&pd_rd_wg=XMlyt&pd_rd_r=3085ead3-b5f5-4866-acf2-4319fd5e8fff)",
      "rating": 3.8
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.125
    },
    "imageUrl": "https://m.media-amazon.com/images/I/61oOyy6AY0L._AC_SS57_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 24.71,
        "oldPrice": null,
        "url": "https://www.amazon.es/Cecotec-Ventilador-EnergySilence-Velocidades-Temporizador/dp/B0BPZSX86X?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:21:52.644Z"
      }
    ],
    "sourceArticles": [
      "ventiladores-techo-vs-torre-vs-columna-comparativa-2026"
    ],
    "confidence": 0.125
  },
  {
    "slug": "cecotec-forcesilence-890-skyline",
    "name": "Cecotec EnergySilence 890 Skyline Digital Tower Fan with Timer and Remote Control, 50 W, 30 Inches (76 cm) Height, Oscillation, Copper Motor, 3 Speeds, 3 Modes, Black",
    "brand": "Cecotec",
    "categoryPath": [
      "electrodomesticos",
      "climatizacion"
    ],
    "description": "[![The perfect last-minute gift](https://m.media-amazon.com/images/I/21j1PbMZccL.png)](https://www.amazon.es/-/en/b/ref=ES_Org_GC_DP_Multi_ILM_Evergreen?_encoding=UTF8&node=3564279031&pd_rd_w=32Wxn&content-id=amzn1.sym.b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_p=b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_r=EF4R6486J8MRR0K4B8Y5&pd_rd_wg=rbd7d&pd_rd_r=b4ea8e24-573a-4b5c-915d-dfab94c63263)",
    "specs": {
      "slug": "cecotec-forcesilence-890-skyline",
      "longdescription": "[![The perfect last-minute gift](https://m.media-amazon.com/images/I/21j1PbMZccL.png)](https://www.amazon.es/-/en/b/ref=ES_Org_GC_DP_Multi_ILM_Evergreen?_encoding=UTF8&node=3564279031&pd_rd_w=32Wxn&content-id=amzn1.sym.b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_p=b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_r=EF4R6486J8MRR0K4B8Y5&pd_rd_wg=rbd7d&pd_rd_r=b4ea8e24-573a-4b5c-915d-dfab94c63263)",
      "rating": 3.8
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.13043478260869565
    },
    "imageUrl": "https://m.media-amazon.com/images/I/61oOyy6AY0L._AC_SS57_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 31.32,
        "oldPrice": null,
        "url": "https://www.amazon.es/Cecotec-Ventilador-Temporizador-EnergySilence-Velocidades/dp/B092JB4Z7J?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:21:57.971Z"
      }
    ],
    "sourceArticles": [
      "ventiladores-techo-vs-torre-vs-columna-comparativa-2026"
    ],
    "confidence": 0.13043478260869565
  },
  {
    "slug": "comfee-mpph-08crn7",
    "name": "COMFEE Penguin Portable Air Conditioner 8000 BTU / 2000 Refrigerators – Air Conditioner without Outdoor Unit – Quiet Low Consumption Cooler with Window Kit | 3x1 Cools, Ventilates and Dehumidifies",
    "brand": "COMFEE",
    "categoryPath": [
      "electrodomesticos",
      "climatizacion"
    ],
    "description": "COMFEE Penguin Portable Air Conditioner 8000 BTU / 2000 Refrigerators – Air Conditioner without Outdoor Unit – Quiet Low Consumption Cooler with Window Kit | 3x1 Cools, Ventilates and Dehumidifies — Aire acondicionado portátil: cuándo encaja (referenced in climatizadores-evaporativos-vs-aire-portatil-comparativa-2026)",
    "specs": {
      "slug": "comfee-mpph-08crn7",
      "rating": 3.9
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.03225806451612903
    },
    "imageUrl": "https://m.media-amazon.com/images/I/41BAMBVfoQL._AC_SR38,50_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 215.64,
        "oldPrice": null,
        "url": "https://www.amazon.es/COMFEE-Ping%C3%BCino-Acondicionado-Port%C3%A1til-Frigor%C3%ADas/dp/B07KJT9PG2?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:22:00.558Z"
      }
    ],
    "sourceArticles": [
      "climatizadores-evaporativos-vs-aire-portatil-comparativa-2026"
    ],
    "confidence": 0.03225806451612903
  },
  {
    "slug": "comfee-mpph-08crn7-aire-portatil",
    "name": "COMFEE Penguin Portable Air Conditioner 3-in-1 | 7000 BTU/1800 Refrigerators with App + Remote Control | Air Conditioner and Dehumidifier | Low Consumption | Follow Me Function | Includes Window Kit",
    "brand": "COMFEE",
    "categoryPath": [
      "electrodomesticos",
      "climatizacion"
    ],
    "description": "COMFEE Penguin Portable Air Conditioner 3-in-1 | 7000 BTU/1800 Refrigerators with App + Remote Control | Air Conditioner and Dehumidifier | Low Consumption | Follow Me Function | Includes Window Kit — Comfee MPPH-08CRN7 (gama básica, dormitorio mediano) (referenced in como-comparar-precios-aire-acondicionado-portatil-espana-2026)",
    "specs": {
      "slug": "comfee-mpph-08crn7-aire-portatil",
      "rating": 3.9
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.03333333333333333
    },
    "imageUrl": "https://m.media-amazon.com/images/I/410+lD0lpPL._AC_SR38,50_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 32.98,
        "oldPrice": null,
        "url": "https://www.amazon.es/COMFEE-Ping%C3%BCino-Acondicionado-Port%C3%A1til-Frigor%C3%ADas/dp/B0CM8P9PV9?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:21:59.324Z"
      }
    ],
    "sourceArticles": [
      "como-comparar-precios-aire-acondicionado-portatil-espana-2026"
    ],
    "confidence": 0.03333333333333333
  },
  {
    "slug": "comfee-mpph-08crn7-portatil-8000-btu",
    "name": "COMFEE Penguin Portable Air Conditioner 8000 BTU / 2000 Refrigerators – Air Conditioner without Outdoor Unit – Quiet Low Consumption Cooler with Window Kit | 3x1 Cools, Ventilates and Dehumidifies",
    "brand": "COMFEE",
    "categoryPath": [
      "electrodomesticos",
      "climatizacion"
    ],
    "description": "COMFEE Penguin Portable Air Conditioner 8000 BTU / 2000 Refrigerators – Air Conditioner without Outdoor Unit – Quiet Low Consumption Cooler with Window Kit | 3x1 Cools, Ventilates and Dehumidifies — Aire acondicionado portátil: cuándo encaja (referenced in aire-acondicionado-portatil-vs-split-comparativa-precio-consumo)",
    "specs": {
      "slug": "comfee-mpph-08crn7-portatil-8000-btu",
      "rating": 3.9
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.0967741935483871
    },
    "imageUrl": "https://m.media-amazon.com/images/I/41BAMBVfoQL._AC_SR38,50_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 215.64,
        "oldPrice": null,
        "url": "https://www.amazon.es/COMFEE-Ping%C3%BCino-Acondicionado-Port%C3%A1til-Frigor%C3%ADas/dp/B07KJT9PG2?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:22:01.849Z"
      }
    ],
    "sourceArticles": [
      "aire-acondicionado-portatil-vs-split-comparativa-precio-consumo"
    ],
    "confidence": 0.0967741935483871
  },
  {
    "slug": "conforama-estructura-pino-135x190",
    "name": "Amazon.es : cama con cajones 135",
    "brand": "Conforama",
    "categoryPath": [
      "muebles",
      "muebles-salon"
    ],
    "description": "[Sponsored ad from What the Sleep. \"With delivery, assembly and removal of used.\" Shop What the Sleep.](https://aax-eu-zaz.amazon.es/x/c/JCpmhJpPEFVmVsQIxgg6cfoAAAGeZYXW-goAAAH2AQBvbm9fdHhuX2JpZDEgICBvbm9fdHhuX2ltcDIgICDT0kfR/clv1c_ek-wBQH2Fbba5jMjPEZX34IogRCZFFeySZuEu3qyiz1xag1omBdKBSwPu93CIdpIuovlqgEULiy2Mhl9Nshl2d6PkUyUmSOVfyGV_srg7Qo1arFFo8P3KTT4Y_d3AFcSXcLWsaXONjso4P1vfsBEU1DZodEMluZK0ED7-x2KfGff3VlB1BANCDT18aiV43LrkNK3ysM7foeJUurl2xtS5nPfeTu6RPrn8IkH3XzmJVOGo1NPFqT0z6XRCMZ-tfbHXA8qEiSKOd4l",
    "specs": {
      "slug": "conforama-estructura-pino-135x190",
      "longdescription": "[Sponsored ad from What the Sleep. \"With delivery, assembly and removal of used.\" Shop What the Sleep.](https://aax-eu-zaz.amazon.es/x/c/JCpmhJpPEFVmVsQIxgg6cfoAAAGeZYXW-goAAAH2AQBvbm9fdHhuX2JpZDEgICBvbm9fdHhuX2ltcDIgICDT0kfR/clv1c_ek-wBQH2Fbba5jMjPEZX34IogRCZFFeySZuEu3qyiz1xag1omBdKBSwPu93CIdpIuovlqgEULiy2Mhl9Nshl2d6PkUyUmSOVfyGV_srg7Qo1arFFo8P3KTT4Y_d3AFcSXcLWsaXONjso4P1vfsBEU1DZodEMluZK0ED7-x2KfGff3VlB1BANCDT18aiV43LrkNK3ysM7foeJUurl2xtS5nPfeTu6RPrn8IkH3XzmJVOGo1NPFqT0z6XRCMZ-tfbHXA8qEiSKOd4l2ZjUbNL8sS1HpKWz7W4I4XtUpcdfC6v_GC-_5d6MV-Lnn8LXGbaLocovh0cY6DTrNFBiy2YMDpAl59OJsRlnAdMakeAyypSR0eti",
      "rating": 4.7
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0
    },
    "imageUrl": "https://m.media-amazon.com/images/I/71pK8ZaDIaL._AC_SR160,134_CB1169409_QL70_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 400,
        "oldPrice": null,
        "url": "https://www.amazon.es/cama-cajones-135/s?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:22:12.577Z"
      }
    ],
    "sourceArticles": [
      "camas-canapes-comparativa-precios-materiales-espana-2026"
    ],
    "confidence": 0
  },
  {
    "slug": "conforama-pack-dormitorio-completo",
    "name": "Geriafy - Electric Articulated Bed | 80 x 190 cm | Reinforced and Compact | Cable Control and Adjustable Legs in 4 Heights",
    "brand": "Geriafy",
    "categoryPath": [
      "muebles",
      "muebles-salon"
    ],
    "description": "Geriafy - Electric Articulated Bed | 80 x 190 cm | Reinforced and Compact | Cable Control and Adjustable Legs in 4 Heights — Conforama: cuándo encaja (referenced in ikea-vs-conforama-vs-maisons-du-monde-comparativa-precios-muebles)",
    "specs": {
      "slug": "conforama-pack-dormitorio-completo",
      "rating": 4.1,
      "reviewcount": 72
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0
    },
    "imageUrl": "https://m.media-amazon.com/images/I/61YASTGdwoL._AC_SX679_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 75.99,
        "oldPrice": null,
        "url": "https://www.amazon.es/Geriafy-Articulada-El%C3%A9ctrica-Reforzada-Regulables/dp/B0DNQGVNYG?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:22:14.563Z"
      }
    ],
    "sourceArticles": [
      "ikea-vs-conforama-vs-maisons-du-monde-comparativa-precios-muebles"
    ],
    "confidence": 0
  },
  {
    "slug": "conforama-sofa-rinconera-chaiselongue",
    "name": "FAVERTI® Super Elastic 3-Seater Sofa Cover from 180 to 230 cm | BUFALI Model | Green | Ideal Cover for Any Shape of Sofa | Quality Protector Jacquard Fabric 3D Cotton Feel",
    "brand": "FAVERTI",
    "categoryPath": [
      "muebles",
      "muebles-salon"
    ],
    "description": "1. [![FAVERTI® Universal Elastic 3-Seater Sofa Cover from 180 to 220 cm | Reale Model | Beige | Protective Sofa Cover | Jacquard Fa](https://m.media-amazon.com/images/I/71l2DXaXQ+L._AC_SS57_.jpg)](https://www.amazon.es/-/en/Universal-Sofa-Reale-Protective-Protector/dp/B0D638XFK4/ref=pd_lpo_d_sccl_1/525-3415518-4418910?pd_rd_w=xM8Cf&content-id=amzn1.sym.dbff13a3-ec7b-4ab4-a8ad-e4356fa2bfdb&pf_rd_p=dbff13a3-ec7b-4ab4-a8ad-e4356fa2bfdb&pf_rd_r=2EPDC82823588XYVFG76&pd_rd_wg=G2yzn&pd_rd_r=24f1009a-2f",
    "specs": {
      "slug": "conforama-sofa-rinconera-chaiselongue",
      "longdescription": "1. [![FAVERTI® Universal Elastic 3-Seater Sofa Cover from 180 to 220 cm | Reale Model | Beige | Protective Sofa Cover | Jacquard Fa](https://m.media-amazon.com/images/I/71l2DXaXQ+L._AC_SS57_.jpg)](https://www.amazon.es/-/en/Universal-Sofa-Reale-Protective-Protector/dp/B0D638XFK4/ref=pd_lpo_d_sccl_1/525-3415518-4418910?pd_rd_w=xM8Cf&content-id=amzn1.sym.dbff13a3-ec7b-4ab4-a8ad-e4356fa2bfdb&pf_rd_p=dbff13a3-ec7b-4ab4-a8ad-e4356fa2bfdb&pf_rd_r=2EPDC82823588XYVFG76&pd_rd_wg=G2yzn&pd_rd_r=24f1009a-2f7f-495c-a7b2-66e9809f48d3&pd_rd_i=B0D638XFK4&psc=1)",
      "rating": 4.4
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.037037037037037035
    },
    "imageUrl": "https://m.media-amazon.com/images/I/71l2DXaXQ+L._AC_SS57_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 56.39,
        "oldPrice": null,
        "url": "https://www.amazon.es/FAVERTI%C2%AE-Funda-Cualquier-sof%C3%A1-Protector/dp/B0DH3WTJXR?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:22:14.157Z"
      }
    ],
    "sourceArticles": [
      "ikea-vs-conforama-vs-maisons-du-monde-comparativa-precios-muebles"
    ],
    "confidence": 0.037037037037037035
  },
  {
    "slug": "delonghi-magnifica-evo",
    "name": "De'Longhi Magnifica Evo - Perfetto Superautomatic Coffee Maker, LatteCrema Automatic Milk Jug, 7 One-Touch Drinks, Soft Touch Controls, Silver and Black (ECAM292.81.SB)",
    "brand": "De'Longhi",
    "categoryPath": [
      "electrodomesticos",
      "grandes-electrodomesticos"
    ],
    "description": "[![The perfect last-minute gift](https://m.media-amazon.com/images/I/21j1PbMZccL.png)](https://www.amazon.es/-/en/b/ref=ES_Org_GC_DP_Multi_ILM_Evergreen?_encoding=UTF8&node=3564279031&pd_rd_w=GsgnT&content-id=amzn1.sym.b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_p=b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_r=P31P78PRZZW6TW0QS3DR&pd_rd_wg=0Djss&pd_rd_r=dfa455aa-1130-4910-a724-015cf90125e3)",
    "specs": {
      "slug": "delonghi-magnifica-evo",
      "longdescription": "[![The perfect last-minute gift](https://m.media-amazon.com/images/I/21j1PbMZccL.png)](https://www.amazon.es/-/en/b/ref=ES_Org_GC_DP_Multi_ILM_Evergreen?_encoding=UTF8&node=3564279031&pd_rd_w=GsgnT&content-id=amzn1.sym.b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_p=b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_r=P31P78PRZZW6TW0QS3DR&pd_rd_wg=0Djss&pd_rd_r=dfa455aa-1130-4910-a724-015cf90125e3)",
      "rating": 4.3
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.08695652173913043
    },
    "imageUrl": "https://m.media-amazon.com/images/I/71Z8Fn4Xb0L._AC_SS57_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 412.4,
        "oldPrice": null,
        "url": "https://www.amazon.es/DeLonghi-Magnifica-Evo-ECAM292-81-SB-especialidades/dp/B0D45RHLSD?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:22:22.055Z"
      }
    ],
    "sourceArticles": [
      "como-comparar-precios-pequeno-electrodomestico-2026"
    ],
    "confidence": 0.08695652173913043
  },
  {
    "slug": "delonghi-magnifica-start-ecam220",
    "name": "De'Longhi Magnifica Start Superautomatic Coffee Maker, Manual Milk Frother, 4 One-Touch Beverages, Soft Touch Controls, Black (ECAM222.20.B)",
    "brand": "De'Longhi",
    "categoryPath": [
      "destacados"
    ],
    "description": "De'Longhi Magnifica Start Superautomatic Coffee Maker, Manual Milk Frother, 4 One-Touch Beverages, Soft Touch Controls, Black (ECAM222.20.B) — Productos hogar recomendados para Prime Day 2026 (referenced in amazon-prime-day-2026-hogar-comparar-precios-falsas-ofertas)",
    "specs": {
      "slug": "delonghi-magnifica-start-ecam220",
      "rating": 4,
      "reviewcount": 136
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.08
    },
    "imageUrl": "https://m.media-amazon.com/images/I/61OVw7YXwwL._AC_SS115_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 247.85,
        "oldPrice": null,
        "url": "https://www.amazon.es/DeLonghi-Magnifica-ECAM222-20-B-Superautom%C3%A1tica-Soft-Touch/dp/B0BV3B7T33?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:22:23.000Z"
      }
    ],
    "sourceArticles": [
      "amazon-prime-day-2026-hogar-comparar-precios-falsas-ofertas"
    ],
    "confidence": 0.08
  },
  {
    "slug": "dreame-l20-ultra",
    "name": "dreame L20 Ultra Robot Aspirador y friegasuelos con MopExtend, Retirada de mopas Robot Aspirador, elevación de mopas, DualBoost 2.0, Vaciado automático, Lavado de mopas, AI Action, 7000Pa, CleanGenius",
    "brand": "Dreame",
    "categoryPath": [
      "electrodomesticos",
      "grandes-electrodomesticos"
    ],
    "description": "dreame L20 Ultra Robot Aspirador y friegasuelos con MopExtend, Retirada de mopas Robot Aspirador, elevación de mopas, DualBoost 2.0, Vaciado automático, Lavado de mopas, AI Action, 7000Pa, CleanGenius — Dreame L20 Ultra (referenced in mejores-aspiradores-robot-con-mopa-2026)",
    "specs": {
      "slug": "dreame-l20-ultra",
      "rating": 4.1,
      "reviewcount": 766
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.16666666666666666
    },
    "imageUrl": "https://m.media-amazon.com/images/I/71sIYPeY8OL._AC_SX569_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 999,
        "oldPrice": null,
        "url": "https://www.amazon.es/Dreame-L20-Ultra-friegasuelos-CleanGenius/dp/B0CF1R9BCQ?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:22:23.346Z"
      }
    ],
    "sourceArticles": [
      "mejores-aspiradores-robot-con-mopa-2026"
    ],
    "confidence": 0.16666666666666666
  },
  {
    "slug": "ecovacs-deebot-n10-plus",
    "name": "ECOVACS DEEBOT N10 Plus Robot Vacuum Cleaner with Mop 4300Pa, Auto Empty Station, 300 min, 400 m2, Laser Navigation TrueMapping 2.0 dToF, Carpet Detection, Custom Cleaning",
    "brand": "ECOVACS",
    "categoryPath": [
      "electrodomesticos",
      "grandes-electrodomesticos"
    ],
    "description": "[![Free delivery on first orders message](https://m.media-amazon.com/images/I/31pWJ-XZqeL.jpg)](https://www.amazon.es/-/en/b/?_encoding=UTF8&node=18978330031&pd_rd_w=nqg2m&content-id=amzn1.sym.57bf98f3-83ad-485b-88b5-01efff37ea63&pf_rd_p=57bf98f3-83ad-485b-88b5-01efff37ea63&pf_rd_r=BY70G5KYC75W6Y1YVKVB&pd_rd_wg=z09Nf&pd_rd_r=8eae1d16-dbff-4944-b2e6-69c539905270)",
    "specs": {
      "slug": "ecovacs-deebot-n10-plus",
      "longdescription": "[![Free delivery on first orders message](https://m.media-amazon.com/images/I/31pWJ-XZqeL.jpg)](https://www.amazon.es/-/en/b/?_encoding=UTF8&node=18978330031&pd_rd_w=nqg2m&content-id=amzn1.sym.57bf98f3-83ad-485b-88b5-01efff37ea63&pf_rd_p=57bf98f3-83ad-485b-88b5-01efff37ea63&pf_rd_r=BY70G5KYC75W6Y1YVKVB&pd_rd_wg=z09Nf&pd_rd_r=8eae1d16-dbff-4944-b2e6-69c539905270)",
      "rating": 3.8,
      "reviewcount": 479
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.16666666666666666
    },
    "imageUrl": "https://m.media-amazon.com/images/I/71qZZ2c0zRL._AC_SX522_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 500,
        "oldPrice": null,
        "url": "https://www.amazon.es/ECOVACS-autom%C3%A1tico-Navegaci%C3%B3n-TrueMapping-Personalizada/dp/B0C85XN54V?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:22:28.033Z"
      }
    ],
    "sourceArticles": [
      "mejores-aspiradores-robot-con-mopa-2026"
    ],
    "confidence": 0.16666666666666666
  },
  {
    "slug": "el-corte-ingles-frigorifico-combi",
    "name": "Midea No Frost Combi Fridge | 59.4 cm Wide x 201 cm High | Stainless Steel | Free Fridge Installation 256 L + 122 L Freezer – Low Consumption Fridge with Vertical Freezer",
    "brand": "Midea",
    "categoryPath": [
      "destacados"
    ],
    "description": "Midea No Frost Combi Fridge | 59.4 cm Wide x 201 cm High | Stainless Steel | Free Fridge Installation 256 L + 122 L Freezer – Low Consumption Fridge with Vertical Freezer — El Corte Inglés Hogar: cuándo encaja (referenced in ikea-vs-leroy-merlin-vs-el-corte-ingles-comparativa-precios-hogar)",
    "specs": {
      "slug": "el-corte-ingles-frigorifico-combi",
      "rating": 4.2,
      "reviewcount": 3
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0.041666666666666664
    },
    "imageUrl": "https://m.media-amazon.com/images/I/313EQflVcfL._AC_SR38,50_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 45,
        "oldPrice": null,
        "url": "https://www.amazon.es/Midea-Frigor%C3%ADfico-Nevera-instalaci%C3%B3n-Congelador/dp/B0GN2VV6CH?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:22:35.317Z"
      }
    ],
    "sourceArticles": [
      "ikea-vs-leroy-merlin-vs-el-corte-ingles-comparativa-precios-hogar"
    ],
    "confidence": 0.041666666666666664
  },
  {
    "slug": "flexispot-e7-160",
    "name": "VASAGLE Electric Desk, Height Adjustable Desk Frame, Dual Motor, 3 Levels Telescopic Legs, 4 Height Memory Function, Cloud White LSD020W01",
    "brand": "VASAGLE",
    "categoryPath": [
      "muebles",
      "muebles-salon"
    ],
    "description": "[![The perfect last-minute gift](https://m.media-amazon.com/images/I/21j1PbMZccL.png)](https://www.amazon.es/-/en/b/ref=ES_Org_GC_DP_Multi_ILM_Evergreen?_encoding=UTF8&node=3564279031&pd_rd_w=4Yggd&content-id=amzn1.sym.b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_p=b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_r=7RB866VM7C2QJ8CR06M8&pd_rd_wg=jQdFE&pd_rd_r=29e2bc69-8fa5-4ced-8150-b8c389ba4cea)",
    "specs": {
      "slug": "flexispot-e7-160",
      "longdescription": "[![The perfect last-minute gift](https://m.media-amazon.com/images/I/21j1PbMZccL.png)](https://www.amazon.es/-/en/b/ref=ES_Org_GC_DP_Multi_ILM_Evergreen?_encoding=UTF8&node=3564279031&pd_rd_w=4Yggd&content-id=amzn1.sym.b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_p=b7ea4ae8-caef-40c7-aaba-4c1601269d86&pf_rd_r=7RB866VM7C2QJ8CR06M8&pd_rd_wg=jQdFE&pd_rd_r=29e2bc69-8fa5-4ced-8150-b8c389ba4cea)",
      "rating": 4.7
    },
    "attributes": {
      "needsReview": true,
      "scrapedConfidence": 0
    },
    "imageUrl": "https://m.media-amazon.com/images/I/61I6UJeQADL._AC_SY300_SX300_QL70_ML2_.jpg",
    "offers": [
      {
        "merchant": "Amazon",
        "merchantDomain": "amazon.es",
        "price": 151.99,
        "oldPrice": null,
        "url": "https://www.amazon.es/-/en/VASAGLE-Electric-Adjustable-Telescopic-LSD020W01/dp/B0BY15T9P7?tag=ahorrhogar-21",
        "scrapedAt": "2026-05-26T18:22:39.188Z"
      }
    ],
    "sourceArticles": [
      "top-10-escritorios-calidad-precio-teletrabajo-2026"
    ],
    "confidence": 0
  }
];
